FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./

RUN npm ci 
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_API_KEY

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_API_KEY=$VITE_SUPABASE_API_KEY
COPY . .

RUN npm run build



FROM nginx:alpine as prod


COPY --from=build  /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



